-- 001_init — initial schema for hydration-drink-ai.
-- Mirrors REQUIREMENTS.md §9. See CLAUDE.md for the rules this schema encodes.
--
-- Two invariants are structural here, not conventional:
--   * logs.id is a client-generated UUID and removals are tombstones
--     (deleted_at), never DELETEs and never a decremented counter. Three
--     sources write to the same day; counters would corrupt silently.
--   * There is no date_of_birth column anywhere, by design. The alcohol gate
--     records only that a check passed and which country's threshold was used.
--
-- Note: no `PRAGMA foreign_keys` here. That pragma is a no-op inside a
-- transaction, and migrations run in one -- so it would silently do nothing.
-- It is set per connection in db.connect() instead.

-- One human. Identities on individual platforms hang off this.
CREATE TABLE users (
    id            TEXT PRIMARY KEY,           -- UUID
    timezone      TEXT NOT NULL,              -- IANA name, e.g. 'Asia/Bangkok'
    bedtime       TEXT,                       -- 'HH:MM' local; drives widget red state
    created_at    TEXT NOT NULL               -- ISO-8601 UTC
);

-- A user may be on Telegram, LINE, and the app simultaneously. A single
-- users.platform column cannot express that, which is why this table exists.
CREATE TABLE platform_identities (
    user_id           TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    platform          TEXT NOT NULL,          -- 'telegram' | 'line' | 'app'
    platform_user_id  TEXT NOT NULL,
    linked_at         TEXT NOT NULL,
    PRIMARY KEY (platform, platform_user_id)
);
CREATE INDEX idx_platform_identities_user ON platform_identities(user_id);

-- Bot -> app handoff. Tokens are stored hashed and are single-use.
CREATE TABLE link_tokens (
    token_hash  TEXT PRIMARY KEY,             -- sha256 of the raw token
    user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    platform    TEXT NOT NULL,                -- platform that issued it
    expires_at  TEXT NOT NULL,
    used_at     TEXT                          -- NULL until redeemed
);
CREATE INDEX idx_link_tokens_user ON link_tokens(user_id);

-- Seed catalog. Nutrition is per serving_size_ml, not per 100ml.
-- source_json holds PER-FIELD provenance; a latte's calories and caffeine
-- routinely come from different places.
CREATE TABLE drinks_catalog (
    id               TEXT PRIMARY KEY,
    name             TEXT NOT NULL,
    category         TEXT NOT NULL,
    subtype          TEXT,
    serving_size_ml  INTEGER NOT NULL,
    calories         REAL,                    -- NULL means unknown, never 0-as-unknown
    sugar_g          REAL,
    caffeine_mg      REAL,
    is_alcohol       INTEGER NOT NULL DEFAULT 0,
    source_json      TEXT NOT NULL,
    fetched_at       TEXT
);
CREATE INDEX idx_drinks_category ON drinks_catalog(category);

CREATE TABLE user_favorites (
    user_id           TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    drink_id          TEXT REFERENCES drinks_catalog(id),
    custom_name       TEXT,
    custom_nutrition  TEXT,                   -- JSON; NULL fields stay NULL
    PRIMARY KEY (user_id, drink_id, custom_name)
);

-- The core log. id is generated by whichever client created the entry, so the
-- same entry arriving twice is applied exactly once.
CREATE TABLE logs (
    id            TEXT PRIMARY KEY,           -- client-generated UUID
    user_id       TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    drink_id      TEXT REFERENCES drinks_catalog(id),
    custom_name   TEXT,                       -- when drink_id is NULL
    quantity      REAL NOT NULL DEFAULT 1,
    logged_at     TEXT NOT NULL,              -- ISO-8601 UTC
    source        TEXT NOT NULL,              -- 'text'|'photo'|'widget'|'app'|'place'
    place_id      TEXT,
    deleted_at    TEXT,                       -- tombstone; NULL means live
    created_at    TEXT NOT NULL,
    CHECK (drink_id IS NOT NULL OR custom_name IS NOT NULL)
);
CREATE INDEX idx_logs_user_time ON logs(user_id, logged_at);
CREATE INDEX idx_logs_user_live ON logs(user_id, deleted_at);

-- Goals ('reach this') and limiters ('do not exceed this') share a table
-- because the widget colours them from the same state machine, inverted.
CREATE TABLE user_goals (
    user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    drink_category  TEXT NOT NULL,
    kind            TEXT NOT NULL CHECK (kind IN ('goal', 'limit')),
    target          REAL NOT NULL,
    period          TEXT NOT NULL DEFAULT 'day',
    active          INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (user_id, drink_category, kind)
);

CREATE TABLE user_settings (
    user_id                   TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    reminders_enabled         INTEGER NOT NULL DEFAULT 1,
    interval_min              INTEGER NOT NULL DEFAULT 120,
    window_start              TEXT NOT NULL DEFAULT '08:00',
    window_end                TEXT NOT NULL DEFAULT '22:00',
    nearby_enabled            INTEGER NOT NULL DEFAULT 1,
    nutrition_replies_enabled INTEGER NOT NULL DEFAULT 1,
    undo_window_sec           INTEGER NOT NULL DEFAULT 4
);

-- Health data. Opt-in, deletable, and never leaves the backend: only the
-- derived target is ever sent anywhere. See CLAUDE.md rule 2.
CREATE TABLE user_health (
    user_id            TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    weight_kg          REAL,
    weight_updated_at  TEXT
);

-- Self-declared age gate. Deliberately stores no date of birth: once the check
-- passes, the age has no reason to exist. See CLAUDE.md rules 3 and 4.
CREATE TABLE user_age_gate (
    user_id           TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    alcohol_unlocked  INTEGER NOT NULL DEFAULT 0,
    country           TEXT,                   -- ISO 3166-1 alpha-2, threshold source
    checked_at        TEXT
);

-- Makes the LINE 300-push/month ceiling visible before it is hit.
CREATE TABLE push_budget (
    user_id     TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    platform    TEXT NOT NULL,
    year_month  TEXT NOT NULL,                -- 'YYYY-MM'
    sent_count  INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, platform, year_month)
);
