"""Domain types shared across the core, adapters, and AI layers.

These are plain dataclasses with no platform or database imports, so the core
stays free of Telegram/LINE/SQLite specifics.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import StrEnum


class LogSource(StrEnum):
    """Where a log entry came from. Recorded so a bad source can be traced."""

    TEXT = "text"
    PHOTO = "photo"
    WIDGET = "widget"
    APP = "app"
    PLACE = "place"


class Platform(StrEnum):
    """A messaging surface, or the app itself."""

    TELEGRAM = "telegram"
    LINE = "line"
    APP = "app"


class GoalKind(StrEnum):
    """A target to reach, or a cap not to exceed."""

    GOAL = "goal"
    LIMIT = "limit"


def new_id() -> str:
    """Generate an entry identifier.

    Entry ids are generated by whichever client creates the entry -- including
    an offline widget -- so that the same entry arriving twice can be applied
    exactly once. See ``logs.upsert_entry``.
    """
    return str(uuid.uuid4())


@dataclass(frozen=True, slots=True)
class LogEntry:
    """One logged drink.

    A removal is represented by ``deleted_at`` being set, never by deleting the
    row and never by decrementing a count elsewhere.
    """

    user_id: str
    logged_at: datetime
    source: LogSource
    id: str = field(default_factory=new_id)
    drink_id: str | None = None
    custom_name: str | None = None
    quantity: float = 1.0
    place_id: str | None = None
    deleted_at: datetime | None = None

    def __post_init__(self) -> None:
        """Validate the invariants the schema also enforces."""
        if self.drink_id is None and self.custom_name is None:
            raise ValueError("a log entry needs either drink_id or custom_name")
        if self.logged_at.tzinfo is None:
            raise ValueError("logged_at must be timezone-aware")
        if self.quantity <= 0:
            raise ValueError("quantity must be positive; removals use deleted_at")

    @property
    def is_live(self) -> bool:
        """Whether this entry counts toward totals."""
        return self.deleted_at is None


@dataclass(frozen=True, slots=True)
class UserSettings:
    """Per-user feature toggles and reminder configuration."""

    user_id: str
    reminders_enabled: bool = True
    interval_min: int = 120
    window_start: str = "08:00"
    window_end: str = "22:00"
    nearby_enabled: bool = True
    nutrition_replies_enabled: bool = True
    undo_window_sec: int = 4


@dataclass(frozen=True, slots=True)
class Goal:
    """A per-category daily goal or limit."""

    user_id: str
    drink_category: str
    kind: GoalKind
    target: float
    period: str = "day"
    active: bool = True
